### ISSUE TITLE
Need documents to describe the difference and benefits of the charts with the official ones

### ISSUE THREAD

**Issue by zeddit** [valeriano-manassero/helm-charts#164]
I heard of the trino chart here is much more mature with the official one, but I cannot figure out the differences underhood. 
Is there any resource for people coming to understand the benefit. great thanks.

**Comment by valeriano-manassero** [comment]
Hi @zeddit ,
before Trino, I created Presto chart because, at the time, installing it on k8s was a bit of a pain. After some time same happened for Trino so I decided to create one just for usage on my clusters.

In fact, this repo contained also other charts (Clear.ML) that, at one point, were migrated to official repositories. The only exception is Trino that started to be widely used here so I proposed a PR to bring my version of the chart to official one but we never merged it even if I know some parts were included after my proposal.

tbh I'm not sure what is the state of official chart so I can't really answer your question but you can download both charts and the do a diff to check.

My guess is that some people prefer this chart just because they can contribute and get their implementation published pretty quickly while probably official one is a bit slower.

**Comment by zeddit** [comment]
Great thanks for your response. I will follow your advice and try both charts.
